package com.tsits.tsmodel.utils;

public class CallStatusDefine {

    public static final byte CALLSTATUE_IDLE    =   0x00;
    public static final byte CALLSTATUE_CALLING =   0x01;
    public static final byte CALLSTATUE_RINGING =   0x02;
    public static final byte CALLSTATUE_CALLWating  =   0x03;
    public static final byte CALLSTATUE_LocalTX   =   0x04;
    public static final byte CALLSTATUE_LocalRX     =   0x05;
    public static final byte CALLSTATUE_CALLIDLE    =   0x06;
    public static final byte CALLSTATUE_CALLEND     =   0x07;
    public static final byte CALLSTATUE_CRATESESSION =100;
    public static final byte CALLSTATUE_DESTROYSESSION=101;


    public static final int CALLCAUSE_DISC_UNKNOWN_OR_NOT_DEFIEND =0x00;
    public static final int CALLCAUSE_DISC_CALL_END =   CALLCAUSE_DISC_UNKNOWN_OR_NOT_DEFIEND+1;
    public static final int CALLCAUSE_DISC_CALLED_PARTY_BUSY    =CALLCAUSE_DISC_CALL_END+1;
    public static final int CALLCAUSE_DISC_CALLED_PARTY_NOT_SUPPORT_ENCRYP  =CALLCAUSE_DISC_CALLED_PARTY_BUSY+1;
    public static final int CALLCAUSE_DISC_CALLED_PARTY_REQ_ENCRYP  =   CALLCAUSE_DISC_CALLED_PARTY_NOT_SUPPORT_ENCRYP+1;
    public static final int CALLCAUSE_DISC_CALLED_PARTY_REJECT_CALL =   CALLCAUSE_DISC_CALLED_PARTY_REQ_ENCRYP+1;
    public static final int CALLCAUSE_DISC_CALLING_PARTY_CANCEL_CALL    =   CALLCAUSE_DISC_CALLED_PARTY_REJECT_CALL+1;
    public static final int CALLCAUSE_DISC_CALLED_RINGING_TIME_OUT      =   CALLCAUSE_DISC_CALLING_PARTY_CANCEL_CALL+1;
    public static final int CALLCAUSE_DISC_CALLING_RINGING_TIME_OUT     =   CALLCAUSE_DISC_CALLED_RINGING_TIME_OUT+1;
    public static final int CALLCAUSE_DISC_NO_ENCRY_DEVICE  =   CALLCAUSE_DISC_CALLING_RINGING_TIME_OUT+1;
    public static final int CALLCAUSE_DISC_CURR_GROUP_NOT_ATTACHED  =   CALLCAUSE_DISC_NO_ENCRY_DEVICE+1;
    public static final int CALLCAUSE_DISC_CHANNEL_BUSY =   50;
    public static final int CALLCAUSE_DISC_INVALID_CALLED_ID    =   CALLCAUSE_DISC_CHANNEL_BUSY+1;
    public static final int CALLCAUSE_DISC_UNKNOWN_CALLED_ID   =   CALLCAUSE_DISC_INVALID_CALLED_ID+1;
    public static final int CALLCAUSE_DISC_CALLED_PARTY_NOT_REGISTER    =   CALLCAUSE_DISC_UNKNOWN_CALLED_ID+1;
    public static final int CALLCAUSE_DISC_CALLED_PARTY_NOT_REACHABLE   =   CALLCAUSE_DISC_CALLED_PARTY_NOT_REGISTER+1;
    public static final int CALLCAUSE_DISC_PREEMPTIVE_USE_OF_RESOURCE   =   CALLCAUSE_DISC_CALLED_PARTY_NOT_REACHABLE+1;
    public static final int CALLCAUSE_DISC_SERVICE_NOT_AVAILABLE        =   CALLCAUSE_DISC_PREEMPTIVE_USE_OF_RESOURCE+1;
    public static final int CALLCAUSE_DISC_INVALID_CALL_ID    =   CALLCAUSE_DISC_SERVICE_NOT_AVAILABLE+1;
    public static final int CALLCAUSE_DISC_SYSTEM_BUSY   =   CALLCAUSE_DISC_INVALID_CALL_ID+1;
    public static final int CALLCAUSE_DISC_MAX_CALL_TIME_REACHED   =   CALLCAUSE_DISC_SYSTEM_BUSY+1;
    public static final int CALLCAUSE_DISC_CALL_RESTORATION_FAILED    =   CALLCAUSE_DISC_MAX_CALL_TIME_REACHED+1;
    public static final int CALLCAUSE_DISC_CALL_REFUSE   =   CALLCAUSE_DISC_CALL_RESTORATION_FAILED+1;
    public static final int CALLCAUSE_DISC_SERVICE_NOT_AUTH   =   CALLCAUSE_DISC_CALL_REFUSE+1;
    public static final int CALLCAUSE_DISC_NETWORK_CONGESTION   =   100;
    public static final int CALLCAUSE_DISC_NO_RESPONSE   =   CALLCAUSE_DISC_NETWORK_CONGESTION+1;
    public static final int CALLCAUSE_DISC_DEVICE_BUSY   =   CALLCAUSE_DISC_NO_RESPONSE+1;
    public static final int CALLCAUSE_DISC_NO_SIGNAL    =   CALLCAUSE_DISC_DEVICE_BUSY+1;
    public static final int CALLCAUSE_DISC_WRONG_INFO   =   CALLCAUSE_DISC_NO_SIGNAL+1;

}

